<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Fo\Module'                        => __DIR__ . '/Module.php',
    'Fo\Controller\UserManagementController' => __DIR__ . '/src/Fo/Controller/UserManagementController.php',
    'FoTest\Framework\TestCase'        => __DIR__ . '/tests/Fo/Framework/TestCase.php',
    'FoTest\SampleTest'                => __DIR__ . '/tests/Fo/SampleTest.php',
);
