<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Management\Module'                        => __DIR__ . '/Module.php',
    'Management\Controller\UserController' => __DIR__ . '/src/Management/Controller/UserController.php',
    'ManagementTest\Framework\TestCase'        => __DIR__ . '/tests/Management/Framework/TestCase.php',
    'ManagementTest\SampleTest'                => __DIR__ . '/tests/Management/SampleTest.php',
);
